### ISSUE TITLE
Pink screen when dragging window between monitors

### ISSUE THREAD

**Issue by Emmsii** [Valkryst/VTerminal#73]
I was testing the [SampleComponents.java](https://github.com/Valkryst/VTerminal/blob/master/test/com/valkryst/VTerminal/samples/component/SampleComponents.java) sample and when dragging the window between my two monitors, this happened.

When dragging from left monitor to right monitor.
![1](https://user-images.githubusercontent.com/2347597/29828181-e19d00aa-8cd3-11e7-8362-b9ebcf7501f8.png)

Then back from right monitor to left monitor.
![2](https://user-images.githubusercontent.com/2347597/29828212-f0352228-8cd3-11e7-9afc-bc14fa95bdfe.png)

The background turned pink and the components turned black. When I dragged the window to the starting monitor the components rendered as normal and the background stayed pink.

**Comment by Valkryst** [comment]
If you switch your Maven dependency to use the following, then most of this issue is resolved with my latest changes. Although it introduced a new bug that I'll need to investigate further.

    <dependency>
        <groupId>com.github.Valkryst</groupId>
        <artifactId>VTerminal</artifactId>
        <version>8cb3bb3</version>
    </dependency>

**Important**

If you're using a single monitor and drag the frame off-screen and back on screen, VTerminal will correctly re-render the Panel.

However, if you drag the screen onto another screen and back on to the original screen, (I think) it causes a deadlock within the standard AWT/Swing libraries and VTerminal will completely freeze.

---

I'll take a better look into this on the weekend, thanks for bringing it up

**Comment by Valkryst** [comment]
Issue resolved in release[ 2.2.0-BETA](https://github.com/Valkryst/VTerminal/releases/tag/2.2.0-BETA).
